<button class="modal-button" id="footer-button">
    Open
</button>

<div class="overlay" id="overlay">
</div>

    <div class="modal" id="modal">

        <button id="modal-close" class="modal-button">X</button>

        <div class="modal-form">
            <label class="modal-form__label" for="guessField">Guess a number from 1 to 50 : </label>
            <input type="number" id="guessField" class="guessField">
            <button type="submit" value="Submit guess" class="buttonSubmit modal-button">guess</button>
        </div>

        <button id="restart-button" class="restartButton modal-button">
            restart game
        </button>

        <div class="results">
            <p class="rightAnswer"></p>
            <p class="lastResult"></p>
            <p class="lowOrHi"></p>
        </div>

    </div>


<script type="text/x-magento-init">
    {
        "*": {
            "jsModal":{}
        }
    }
</script>

<!--<script type="text/x-magento-init">-->
<!--    {-->
<!--        "*": {-->
<!--            "jqueryModal":{}-->
<!--        }-->
<!--    }-->
<!--</script>-->


