<!--<button id="footer-button">-->
<!--    Open-->
<!--</button>-->
<!---->
<!--<div class="overlay" id="overlay">-->
<!--    <div class="modal" id="modal">-->
<!---->
<!--        <button id="modal-close">X</button>-->
<!---->
<!--        <div class="modal-form">-->
<!--            <label class="modal-form__label" for="guessField">Guess a number from 1 to 50 : </label>-->
<!--            <input type="number" id="guessField" class="guessField">-->
<!--            <button type="submit" value="Submit guess" class="buttonSubmit">guess</button>-->
<!--        </div>-->
<!---->
<!--        <div class="results">-->
<!--            <p class="rightAnswer"></p>-->
<!--            <p class="lastResult"></p>-->
<!--            <p class="lowOrHi"></p>-->
<!--        </div>-->
<!---->
<!--        <button id="restart-button" class="restartButton button">-->
<!--            restart game-->
<!--        </button>-->
<!--    </div>-->
<!--</div>-->

<!--<script type="text/x-magento-init">-->
<!--    {-->
<!--        "*": {-->
<!--            "jsModal":{}-->
<!--        }-->
<!--    }-->
<!--</script>-->

<!--<script type="text/x-magento-init">-->
<!--    {-->
<!--        "*": {-->
<!--            "jqueryModal":{}-->
<!--        }-->
<!--    }-->
<!--</script>-->


