<div id="footer-button">
    Open
</div>

<div class="overlay" id="overlay">
    <div class="modal" id="modal">

        <button id="modal-close">X</button>

        <div class="form">
            <label for="guessField">Guess a number : </label>
            <input type="text" id="guessField" class="guessField">
            <button type="submit" value="Submit guess" class="guessSubmit">submit</button>
        </div>

        <div class="resultParas text-center lead">
            <p class="guesses"></p>
            <p class="lastResult"></p>
            <p class="lowOrHi"></p>
        </div>
    </div>
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "modal":{}
        }
    }
</script>
